name: matrix
description: Matrix Dart SDK
version: 0.2.0
homepage: https://famedly.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  mime: ^1.0.0
  canonical_json: ^1.0.0
  markdown: ^4.0.0
  html_unescape: ^2.0.0
  moor: ">=4.0.0 <=4.3.2"
  random_string: ^2.1.0
  crypto: ^3.0.0
  base58check: ^2.0.0
  olm: ^2.0.0
  matrix_api_lite:
    git:
      url: https://github.com/mkc188/matrix_api_lite.git
      ref: e4e0845
  hive: ^2.0.4
  ffi: ^1.0.0
  js: ^0.6.3
  slugify: ^2.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.15.7
  coverage: ">=0.15.0 <2.0.0"
  moor_generator: ^4.0.0
  build_runner: ^1.11.1
  file: ^6.1.1
  #flutter_test: {sdk: flutter}
